In [1]:
%pwd

'/teamspace/studios/this_studio/RAG/research'

In [2]:
%cd /teamspace/studios/this_studio/RAG

/teamspace/studios/this_studio/RAG


/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [3]:
import torch

In [4]:
h_residuals_tensors = torch.load("h_residuals_eval.pt",map_location=torch.device('cpu'))
hl_residuals_tensors = torch.load("h_residuals_eval.pt",map_location=torch.device('cpu'))


In [5]:
len(h_residuals_tensors),len(hl_residuals_tensors)

(8, 8)

In [6]:
h_residuals_tensors[3][0].shape

torch.Size([1, 23, 4096])

In [7]:
h_residuals = [[] for i in range(33)]
hl_residuals = [[] for i in range(33)]
for i in h_residuals_tensors:
    for j in range(33):
        for k in i[j].squeeze():
            h_residuals[j].append(k)
for i in hl_residuals_tensors:
    for j in range(33):
        for k in i[j].squeeze():
            hl_residuals[j].append(k)
h_residuals = [torch.stack(i) for i in h_residuals]
hl_residuals = [torch.stack(i) for i in hl_residuals]
h_residuals_tensor = torch.stack(h_residuals)
hl_residuals_tensor = torch.stack(hl_residuals)
hl_residuals_tensor = hl_residuals_tensor.squeeze()
h_residuals_tensor = h_residuals_tensor.squeeze()

hl_residuals_tensor = torch.reshape(hl_residuals_tensor,(33,-1,4096))
h_residuals_tensor = torch.reshape(h_residuals_tensor,(33,-1,4096))

In [8]:
h_residuals_tensor.shape,hl_residuals_tensor.shape

(torch.Size([33, 154, 4096]), torch.Size([33, 154, 4096]))

In [9]:
hl_residuals_tensor = hl_residuals_tensor[:,:943,:]

In [10]:
residuals_tensor = []
for i in residuals:
    residuals_tensor.append(torch.stack(i))
h_residuals = residuals_tensor[:42]
hl_residuals = residuals_tensor[42:]
h_residuals_tensor = torch.stack(h_residuals)
hl_residuals_tensor = torch.stack(hl_residuals)
hl_residuals_tensor = hl_residuals_tensor.squeeze()
h_residuals_tensor = h_residuals_tensor.squeeze()
hl_residuals_tensor = torch.reshape(hl_residuals_tensor,(33,-1,4096))
h_residuals_tensor = torch.reshape(h_residuals_tensor,(33,-1,4096))

NameError: name 'residuals' is not defined

In [11]:
hl_residuals_tensor.shape

torch.Size([33, 154, 4096])

In [12]:
h_mean = []
hl_mean = []
for i in h_residuals_tensor:
    h_mean.append(i.mean(0))
for i in hl_residuals_tensor:
    hl_mean.append(i.mean(0))
h_mean = torch.stack(h_mean)
hl_mean = torch.stack(hl_mean)
h_mean.shape

torch.Size([33, 4096])

In [13]:
torch.save(hl_mean,"hl_mean.pt")
torch.save(h_mean,"h_mean.pt")

In [14]:
hl_mean = torch.load("hl_mean.pt")
h_mean = torch.load("h_mean.pt")

In [15]:
mean_diff = hl_mean - h_mean
mean_diff.shape

torch.Size([33, 4096])

In [16]:
mean_diff

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], dtype=torch.float16,
       grad_fn=<SubBackward0>)

In [17]:
h_residuals_eval_tensors = torch.load("h_residuals_eval.pt",map_location=torch.device('cpu'))
hl_residuals_eval_tensors = torch.load("hl_residuals_eval.pt",map_location=torch.device('cpu'))

In [18]:
h_residuals = [[] for i in range(33)]
hl_residuals = [[] for i in range(33)]
for i in h_residuals_eval_tensors:
    for j in range(33):
        for k in i[j].squeeze():
            h_residuals[j].append(k)
for i in hl_residuals_eval_tensors:
    for j in range(33):
        for k in i[j].squeeze():
            hl_residuals[j].append(k)
h_residuals = [torch.stack(i) for i in h_residuals]
hl_residuals = [torch.stack(i) for i in hl_residuals]
h_residuals_tensor = torch.stack(h_residuals)
hl_residuals_tensor = torch.stack(hl_residuals)
hl_residuals_tensor = hl_residuals_tensor.squeeze()
h_residuals_tensor = h_residuals_tensor.squeeze()

hl_residuals_tensor = torch.reshape(hl_residuals_tensor,(33,-1,4096))
h_residuals_tensor = torch.reshape(h_residuals_tensor,(33,-1,4096))

In [19]:
h_residuals_tensor = h_residuals_tensor[:,:100,:]
hl_residuals_tensor = hl_residuals_tensor[:,:100,:]
h_residuals_tensor.shape

torch.Size([33, 100, 4096])

In [20]:
torch.cat([h_residuals_tensor,hl_residuals_tensor],axis=1).shape

torch.Size([33, 200, 4096])

In [21]:
validation_labels = torch.stack([*torch.zeros(100),*torch.ones(100)])
validation_labels

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])

In [22]:
import torch

# Step 1: Calculate Mean Difference Vectors (Example data)
mean_diff_vectors = mean_diff  # Example mean difference vectors

# Step 2: Normalize the Mean Difference Vectors
normalized_diff_vectors = mean_diff_vectors / mean_diff_vectors.norm(dim=1, keepdim=True)

# Step 3: Evaluate Each Normalized Direction
def evaluate_direction(direction, validation_data):
    projections = validation_data @ direction.T
    harmful_projections = projections[validation_labels == 1]
    non_harmful_projections = projections[validation_labels == 0]
    score = (harmful_projections.mean() - non_harmful_projections.mean()).abs()
    return score.item()

# Example validation data and labels
validation_data = torch.cat([h_residuals_tensor,hl_residuals_tensor],axis=1) # Example validation data
validation_labels = torch.stack([*torch.ones(100),*torch.zeros(100)])  # Binary labels (0: non-harmful, 1: harmful)

scores = [evaluate_direction(direction, validation_data[i]) for i,direction in enumerate(normalized_diff_vectors)]

# Step 4: Select the Best Direction
best_direction_index = torch.argmax(torch.tensor(scores))
optimal_refusal_direction = normalized_diff_vectors[best_direction_index]

print("Optimal Refusal Direction (Layer):", best_direction_index)
print("Optimal Refusal Direction Vector:", optimal_refusal_direction)


Optimal Refusal Direction (Layer): tensor(0)
Optimal Refusal Direction Vector: tensor([nan, nan, nan,  ..., nan, nan, nan], dtype=torch.float16,
       grad_fn=<SelectBackward0>)


/tmp/ipykernel_28719/3156558793.py:11: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3637.)
  projections = validation_data @ direction.T


In [23]:
normalized_diff_vectors[32]

tensor([nan, nan, nan,  ..., nan, nan, nan], dtype=torch.float16,
       grad_fn=<SelectBackward0>)

In [24]:
# Assuming you have a function to compute the score for each direction
def evaluate_direction(direction, validation_data):
    # Project validation data onto the direction
    projections = validation_data @ direction.T
    # Compute some score, e.g., difference in means, classification accuracy, etc.
    score = compute_score(projections)
    return score

validation_data = torch.randn(100, 4096)  # Example validation data
scores = [evaluate_direction(direction, validation_data) for direction in normalized_diff_vectors]


RuntimeError: expected scalar type Float but found Half

In [38]:
len(sums)

33

In [158]:
mean_diff

tensor([[ 0.0445, -0.0067, -0.0494,  ...,  0.0464,  0.0305, -0.0188],
        [ 0.1372,  0.0489, -0.0144,  ...,  0.0309, -0.0786, -0.0573],
        [ 0.0542,  0.0238,  0.0421,  ..., -0.0037, -0.0235, -0.0103],
        ...,
        [ 0.0949,  0.1027, -0.0589,  ...,  0.1155,  0.0649, -0.0217],
        [-0.0548, -0.1085,  0.0116,  ...,  0.0891,  0.0804,  0.0151],
        [ 0.1182,  0.0590,  0.0128,  ...,  0.0050, -0.0399, -0.0374]],
       dtype=torch.float16, grad_fn=<SubBackward0>)

In [35]:
torch.save(mean_diff,"mean_diff1.pt")

In [153]:
mean_diff

tensor([[-0.0323, -0.0023, -0.0378,  ...,  0.0029,  0.0023, -0.0116],
        [-0.1018,  0.0226, -0.1803,  ...,  0.0419, -0.0576, -0.1185],
        [ 0.0278, -0.0320, -0.0507,  ...,  0.0207, -0.0487,  0.0005],
        ...,
        [-0.0504, -0.0121,  0.0203,  ...,  0.0235, -0.0176, -0.0512],
        [-0.0494, -0.0894,  0.0415,  ...,  0.0504, -0.0562,  0.0295],
        [ 0.1012, -0.0847, -0.1178,  ..., -0.2128,  0.1364,  0.0286]],
       dtype=torch.float16, grad_fn=<SubBackward0>)

In [114]:
h_residuals = residuals[:42]
hl_residuals = residuals[42:]

In [132]:
42*26

1092

In [102]:
harmfull_residuals=[]
harmless_residuals=[]
for i in h_residuals:
    for j in i:
        for k in j.squeeze():
            harmfull_residuals.append(k)
for i in hl_residuals:
    for j in i:
        for k in j.squeeze():
            harmless_residuals.append(k)

In [103]:
harmfull_residuals,harmless_residuals=harmfull_residuals[:len(harmfull_residuals)//2],harmfull_residuals[len(harmfull_residuals)//2:]

In [105]:
len(harmfull_residuals)

18018

In [106]:
harmfull_residuals = torch.stack(harmfull_residuals)
harmless_residuals = torch.stack(harmless_residuals)

In [107]:
h_mean=harmfull_residuals.mean(0)
hl_mean=harmless_residuals.mean(0)

In [108]:
mean = hl_mean-h_mean

In [109]:
mean

tensor([ 0.0138, -0.0013, -0.0062,  ..., -0.0095, -0.0127, -0.0044],
       dtype=torch.float16, grad_fn=<SubBackward0>)

In [92]:
torch.save(mean,"mean.pt")

In [110]:
mean = torch.load("mean.pt")

In [111]:
mean

tensor([0.0792, 0.0333, 0.0212,  ..., 0.0326, 0.0004, 0.0040],
       dtype=torch.float16, requires_grad=True)